# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nkoutrel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/04 14:40:41 by nkoutrel          #+#    #+#              #
#    Updated: 2016/11/04 14:40:44 by nkoutrel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

C_FLAGS = -Wall -Wextra -Werror -c

HEADERS = libft.h

CC = gcc

SRC_DIR = ./

OBJ_DIR = ./

C_FILES =	ft_memset.c \
			ft_bzero.c \
			ft_memcpy.c \
			ft_memccpy.c \
			ft_memmove.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_strlen.c \
			ft_strdup.c \
			ft_strcpy.c \
			ft_strncpy.c \
			ft_strcat.c \
			ft_strncat.c \
			ft_strlcat.c \
			ft_strchr.c \
			ft_strrchr.c \
			ft_strstr.c \
			ft_strnstr.c \
			ft_strcmp.c \
			ft_strncmp.c \
			ft_atoi.c \
			ft_isalpha.c \
			ft_isdigit.c \
			ft_isalnum.c \
			ft_isascii.c \
			ft_isprint.c \
			ft_toupper.c \
			ft_tolower.c \
			ft_memalloc.c \
			ft_memdel.c \
			ft_strnew.c \
			ft_strdel.c \
			ft_strclr.c \
			ft_striter.c \
			ft_striteri.c \
			ft_strmap.c \
			ft_strmapi.c \
			ft_strequ.c \
			ft_strnequ.c \
			ft_strsub.c \
			ft_strjoin.c \
			ft_strtrim.c \
			ft_strsplit.c \
			ft_itoa.c \
			ft_putchar.c \
			ft_putstr.c \
			ft_putendl.c \
			ft_putnbr.c \
			ft_putchar_fd.c \
			ft_putstr_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			w_count.c \
			ft_dig_counter.c \
			ft_abs.c \
			ft_lstnew.c \
			ft_lstdelone.c \
			ft_lstdel.c \
			ft_lstadd.c \
			ft_lstiter.c \
			ft_lstmap.c \
			ft_isupper.c \
			ft_islower.c \
			ft_strdouble.c \

SOURCES = $(addprefix $(SRC_DIR), $(C_FILES))

OBJECTS = $(addprefix $(OBJ_DIR), $(patsubst %.c, %.o, $(C_FILES)))

default: all

all:	$(NAME)

$(NAME):
	$(CC) $(C_FLAGS) -c $(C_FILES) -I$(HEADERS)
	ar rc $(NAME) $(OBJECTS)
	ranlib $(NAME)

fclean:	clean
	/bin/rm -rf $(NAME)

clean:
	/bin/rm -rf $(OBJECTS)

re:	fclean $(NAME)

.PHONY : clean fclean re